### ISSUE TITLE
add validations based on swagger spec

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-inflector#9]
We currently do type validation but not constraints.

**Comment by jasonh-n-austin** [comment]
The other big category that comes to mind is custom format validation.

**Comment by webron** [comment]
@jasonh-n-austin - good point, but that should be a separate ticket. This issue refers to the JSON Schema validation attributes and not to format validation which are type extensions (known or custom ones).

**Comment by jasonh-n-austin** [comment]
@webron totally not getting what you're describing, but I'll put in another ticket with what I was thinking.

**Comment by webron** [comment]
@jasonh-n-austin - sorry about that. The idea behind this issue was to add support for validation properties such as `minLength`, `pattern` and so on.

Completely understand the need for `format` validation extensions as well, but since that's likely to be a different aspect of the implementation, it should be done in a separate ticket.

**Comment by fehguy** [comment]
We can just use json schema to validate the input docs.  Will look at adding that in a future version as there are many edge cases to check with the schema (like remote references, etc).

**Comment by fehguy** [comment]
Fixed in https://github.com/swagger-api/swagger-inflector/commit/fa0783814af2fb530e347d8e659a277a6fc5f17e
